-- Done by Cloud Service layer, uses compute capacity.
-- Does not need a warehouse selected to run

-- SYSADMIN or ACCOUNTADMIN can make a warehouse
USE ROLE SYSADMIN;

CREATE ROLE ROLE_FLIGHT_WEATHER_ETL;
GRANT ROLE ROLE_FLIGHT_WEATHER_ETL to USER TPETRANGELO;

CREATE OR REPLACE WAREHOUSE FLIGHT_WEATHER_INGEST_WH
WITH
WAREHOUSE_SIZE = XSMALL
-- MIN_CLUSTER_COUNT = 1 --used if multicluster is active
-- MAX_CLUSTER_COUNT = 3 --used if multicluster is active
AUTO_RESUME = TRUE
INITIALLY_SUSPENDED = TRUE
AUTO_SUSPEND = 300
COMMENT = 'NEW FLIGHT WEATHER INGEST WAREHOUSE';

CREATE OR REPLACE WAREHOUSE FLIGHT_WEATHER_TRANSFORM_WH
WITH
WAREHOUSE_SIZE = SMALL
-- MIN_CLUSTER_COUNT = 1 --used if multicluster is active
-- MAX_CLUSTER_COUNT = 3 --used if multicluster is active
AUTO_RESUME = TRUE
INITIALLY_SUSPENDED = TRUE
AUTO_SUSPEND = 300
COMMENT = 'NEW FLIGHT WEATHER TRANSFORM WAREHOUSE';

GRANT USAGE ON FLIGHT_WEATHER_INGEST_WH TO ROLE_FLIGHT_WEATHER_ETL;
GRANT USAGE ON FLIGHT_WEATHER_TRANSFORM_WH TO ROLE_FLIGHT_WEATHER_ETL;

-- ALTER WAREHOUSE FLIGHT_WEATHER_WH RESUME starts up WH
-- ALTER WAREHOUSE FLIGHT_WEATHER_WH SET WAREHOUSE_SIZE = SMALL changes WH size. SET changes properties/changes values
