-- ACCOUNTADMIN Or SYSADMIN can be used
USE ROLE SYSADMIN;

CREATE DATABASE IF NOT EXISTS FLIGHT_WEATHER;

CREATE SCHEMA IF NOT EXISTS FLIGHT_WEATHER.INGEST;
CREATE SCHEMA IF NOT EXISTS FLIGHT_WEATHER.BRONZE;
CREATE SCHEMA IF NOT EXISTS FLIGHT_WEATHER.SILVER;
CREATE SCHEMA IF NOT EXISTS FLIGHT_WEATHER.GOLD;