USE DATABASE FLIGHT_WEATHER;
USE SCHEMA INGEST;

CREATE STAGE IF NOT EXISTS STG_FLIGHTS_BRONZE
  URL = 's3://flight-weather-de-project/bronze/aerodatabox/'
  STORAGE_INTEGRATION = S3_INT_FLIGHT_WEATHER
  FILE_FORMAT = FF_PARQUET;

CREATE STAGE IF NOT EXISTS STG_WEATHER_BRONZE
  URL = 's3://flight-weather-de-project/bronze/openweather/'
  STORAGE_INTEGRATION = S3_INT_FLIGHT_WEATHER
  FILE_FORMAT = FF_PARQUET;