-- Verify rows loaded
SELECT COUNT(*) AS flights_rows FROM BRONZE.FLIGHTS;
SELECT COUNT(*) AS weather_rows FROM BRONZE.WEATHER;

-- Verify copy history (optional)
SELECT *
FROM TABLE(INFORMATION_SCHEMA.COPY_HISTORY(
  TABLE_NAME=>'FLIGHT_WEATHER.BRONZE.WEATHER',
  START_TIME=>DATEADD('hour', -24, CURRENT_TIMESTAMP())
));