USE ROLE ROLE_FLIGHT_WEATHER_ETL;
USE WAREHOUSE FLIGHT_WEATHER_INGEST_WH;
USE DATABASE FLIGHT_WEATHER;
USE SCHEMA BRONZE;

SELECT
  'FLIGHTS' AS table_name,
  COUNT(*)  AS row_count,
  MAX(loaded_at) AS max_loaded_at
FROM BRONZE.FLIGHTS
UNION ALL
SELECT
  'WEATHER' AS table_name,
  COUNT(*)  AS row_count,
  MAX(loaded_at) AS max_loaded_at
FROM BRONZE.WEATHER;
