services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - airflow_pgdata:/var/lib/postgresql/data
    restart: unless-stopped


  airflow-init:
    profiles: ["init"]
    build:
      context: ..
      dockerfile: docker/airflow/Dockerfile
    depends_on:
      - postgres
    env_file:
      - ../.env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__SECRET_KEY: "REDACTED"
    volumes:
      - ../airflow/dags:/opt/airflow/dags
      - ../:/opt/airflow/project
      - airflow_logs:/opt/airflow/logs
      - ../secrets/rsa_key.p8:/opt/airflow/project/secrets/rsa_key.p8:ro
    entrypoint: /bin/bash
    command:
      - -lc
      - |
        set -e
        airflow db init

        airflow users create \
          --username admin \
          --password admin \
          --firstname Admin \
          --lastname User \
          --role Admin \
          --email admin@example.com || true

        airflow users reset-password --username admin --password admin

  airflow-webserver:
    <<: &airflow-common
      build:
        context: ..
        dockerfile: docker/airflow/Dockerfile
      depends_on:
        - postgres
      env_file:
        - ../.env
      environment:
        AIRFLOW__CORE__EXECUTOR: LocalExecutor
        AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
        AIRFLOW__CORE__LOAD_EXAMPLES: "false"
        
        # Logs (shared volume)
        AIRFLOW__LOGGING__BASE_LOG_FOLDER: /opt/airflow/logs

        # Webserver config
        AIRFLOW__WEBSERVER__SECRET_KEY: "REDACTED"

      volumes:
        - ../airflow/dags:/opt/airflow/dags
        - ../:/opt/airflow/project
        - airflow_logs:/opt/airflow/logs
        - ../secrets/rsa_key.p8:/opt/airflow/project/secrets/rsa_key.p8:ro
        - ../dbt/profiles:/opt/airflow/dbt_profiles

    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "false"
      AIRFLOW__WEBSERVER__SECRET_KEY: "REDACTED"
      AIRFLOW__LOGGING__BASE_LOG_FOLDER: /opt/airflow/logs



    command: webserver
    restart: unless-stopped


  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    restart: unless-stopped


volumes:
  airflow_pgdata:
  airflow_logs:
